name: "Test Action"
description: "test action"
inputs:
  api_endpoint:
    description: "Boost API endpoint"
    required: false
    default: https://api.boostsecurity.io
  api_token:
    description: "Boost API token"
    required: true
  modules_path:
    description: "Path to the modules directory"
    required: false
    default: "scanners/"
  rules_realm_path:
    description: "Path to the rules realm directory"
    required: false
    default: "rules-reaml/"
  docs_url:
    description: "URL to the documentation"
    required: false
    default: "https://docs.boostsecurity.io"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install poetry
      run: pip3 install --pre "poetry==1.4.2"
      shell: bash
    - name: Install dependencies
      run: |
        cp ${{ github.action_path }}/pyproject.toml ${{ github.action_path }}/poetry.lock . && \
          poetry install --no-root --without dev
      shell: bash
    - uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.11.1
      id: changes
      with:
        filters: |
          rules:
          - '**/rules.yaml'
    - name: Validate rules database
      if: steps.changes.outputs.rules == 'true'
      run: |
        poetry run python -m boostsec.registry_validator.validate_rules_db \
          --scanners-path ${{ inputs.modules_path }} --rules-realm-path ${{ inputs.rules_realm_path }}
      shell: bash
      env:
        PYTHONPATH: ${{ github.action_path }}
        BOOSTSEC_DOC_BASE_URL: ${{ inputs.docs_url }}
    - name: Validate namespaces
      run: |
        poetry run python -m boostsec.registry_validator.validate_namespaces \
          --modules-path ${{ inputs.modules_path }}
      shell: bash
      env:
        PYTHONPATH: ${{ github.action_path }}
    - name: Upload rules database
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run: |
        poetry run python -m boostsec.registry_validator.upload_rules_db \
          --api-endpoint ${{ inputs.api_endpoint }} --api-token ${{ inputs.api_token }} \
          --scanners-path ${{ inputs.modules_path }} --rules-realm-path ${{ inputs.rules_realm_path }}
      shell: bash
      env:
        PYTHONPATH: ${{ github.action_path }}
        BOOSTSEC_DOC_BASE_URL: ${{ inputs.docs_url }}
