name: "Test Action"
description: "test action"
inputs:
  rules_db_path:
    description: "Path to the rules database"
    required: false
    default: "scanners/"
  modules_path:
    description: "Path to the modules directory"
    required: false
    default: "scanners/"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install poetry
      run: pip3 install --pre "poetry==1.2.0b1"
      shell: bash
    - name: Install dependencies
      run: |
        cp ${{ github.action_path }}/pyproject.toml ${{ github.action_path }}/poetry.lock . && \
          poetry install --no-root --without dev
      shell: bash
    - name: Validate rules database
      run: |
        poetry run python ${{ github.action_path }}/boostsec/registry_validator/validate_rules_db.py \
          --rules-db-path ${{ inputs.rules_db_path }}
      shell: bash
    - name: Validate namespaces
      run: |
        poetry run python ${{ github.action_path }}/boostsec/registry_validator/validate_namespaces.py \
          --modules-path ${{ inputs.modules_path }}
      shell: bash
